name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your codebase
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Node.js and cache dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      # 3. Install Firebase Function dependencies
      - name: Install Function Dependencies
        run: cd functions && npm ci

      # 4. Skip lint (avoids error if not configured)
      - name: Skip Lint
        run: echo "Skipping lint step"

      # 5. Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6. Authenticate using Service Account Key (stored in GitHub Secrets)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 7. Deploy Hosting and Functions (no token needed)
      - name: Deploy to Firebase
        run: |
          firebase deploy --project leadradar-99bac --non-interactive

      # 8. Make 'placesTextSearch' publicly invokable
      - name: Set Permissions for placesTextSearch
        run: >
          gcloud functions add-iam-policy-binding placesTextSearch
          --project=leadradar-99bac
          --region=us-central1
          --member="allUsers"
          --role="roles/cloudfunctions.invoker"

      # 9. Make 'pageSpeedProxy' publicly invokable
      - name: Set Permissions for pageSpeedProxy
        run: >
          gcloud functions add-iam-policy-binding pageSpeedProxy
          --project=leadradar-99bac
          --region=us-central1
          --member="allUsers"
          --role="roles/cloudfunctions.invoker"
